stages:
  - deploy

deploy_compose:
  stage: deploy
  script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      #- cp -p ../acme.json ./traefik/acme.json
      - docker-compose -f docker-compose.yml down || true
      - docker-compose -f docker-compose.yml up -d
  tags:
    - shell
