---
- name: Install Clickhouse
  hosts: clickhouse-01
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.systemd:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Errors
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "/home/svil/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            mode: "0644"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "/home/svil/{{ item }}_{{ clickhouse_version }}_amd64.deb"
      loop:
        - clickhouse-common-static
        - clickhouse-client
        - clickhouse-server
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
    - name: Установить Vector бинарник напрямую
      become: true
      ansible.builtin.get_url:
       url: https://github.com/vectordotdev/vector/releases/download/v0.50.0/vector-0.50.0-x86_64-unknown-linux-gnu.tar.gz
       dest: /usr/local/bin/vector.tar.gz
       mode: '0644'

    - name: Распаковать Vector
      become: true
      ansible.builtin.unarchive:
        src: /usr/local/bin/vector.tar.gz
        dest: /usr/local
        remote_src: yes
        creates: /opt/vector-0.50.0/bin/vector
    - name: Создать systemd сервис
      become: true
      ansible.builtin.copy:
       content: |
        [Unit]
        Description=Vector
        After=network.target

        [Service]
        ExecStart=/usr/local/vector-0.50.0/bin/vector
        Restart=always

        [Install]
        WantedBy=multi-user.target
       dest: /etc/systemd/system/vector.service

    - name: Запустить Vector
      become: true
      ansible.builtin.systemd:
       name: vector
       enabled: yes
       state: started
    - name: Install nginx
      become: true
      ansible.builtin.apt:
       name: nginx
       state: present
       allow_downgrade: yes
    - name: Create a directory
      become: true
      ansible.builtin.file:
       path: /home/svil/git
       state: directory
       mode: '0755'
    - name: Clone a repo
      become: true 
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: /home/svil/git
    - name: config
      become: true
      ansible.builtin.template:
        src: default
        dest: /etc/nginx/sites-available/default
        mode: '0644'
    - name: chmod 755 /home/svil
      file:
       path: /home/svil
       mode: '0755'

    - name: chmod 755 /home/svil/git
      file:
       path: /home/svil/git
       mode: '0755'

    - name: chmod 644 /home/svil/git/index.html
      file:
       path: /home/svil/git/index.html
       mode: '0644'

    - name: restart nginx
      become: true
      systemd:
        name: nginx
        state: restarted
