[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.traefik]
    address = ":10001"

    [entryPoints.traefik.http.tls]
      certResolver = "lets-encrypt"

  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

    [entryPoints.websecure.http.tls]
      certResolver = "lets-encrypt"

[api]
   dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "agukalov@newsmedia.ru"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.httpChallenge]
    entryPoint="web"

[providers.docker]
  watch = true
  network = "web"
  exposedByDefault = false

[providers.file]
  filename = "traefik_dynamic.toml"

[experimental.localplugins.extractcookie]
   modulename = "nm/extractcookie"
