
[http.middlewares.dashAuth.basicAuth]
  users = [
    "traefik:$2y$05$xkW2gKa066U2VnUItBbCSOuVFCItuDTkNvDMuIJ/rLTXgMWf.ZPCe"
  ]

  
[http.routers.dashboard]
  rule = "Host(`ym.corr.life`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
  #rule = "(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
  #entrypoints = ["web","websecure"]
  entrypoints = ["websecure"]
  middlewares = ["dashAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

