---
clickhouse_version: "25.10.6.36"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
vector_version: "0.44.0-1"
vector_packages:
  - vector
docker_image: "nginx"
docker_tag: "latest"
ca_path: ""
timeout: 120
lighthouse_version: "11.8.0"
